// Generated by gencpp from file kinect/KinectCommand.msg
// DO NOT EDIT!


#ifndef KINECT_MESSAGE_KINECTCOMMAND_H
#define KINECT_MESSAGE_KINECTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinect
{
template <class ContainerAllocator>
struct KinectCommand_
{
  typedef KinectCommand_<ContainerAllocator> Type;

  KinectCommand_()
    : start(0)
    , objNum(0)  {
    }
  KinectCommand_(const ContainerAllocator& _alloc)
    : start(0)
    , objNum(0)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;

   typedef uint8_t _objNum_type;
  _objNum_type objNum;




  typedef boost::shared_ptr< ::kinect::KinectCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect::KinectCommand_<ContainerAllocator> const> ConstPtr;

}; // struct KinectCommand_

typedef ::kinect::KinectCommand_<std::allocator<void> > KinectCommand;

typedef boost::shared_ptr< ::kinect::KinectCommand > KinectCommandPtr;
typedef boost::shared_ptr< ::kinect::KinectCommand const> KinectCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect::KinectCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect::KinectCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kinect': ['/home/marouane/Documents/fp_workspace/rosCode/src/kinect/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect::KinectCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect::KinectCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect::KinectCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect::KinectCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect::KinectCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect::KinectCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect::KinectCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2394b59af5274a47f8538009ed2d9f9";
  }

  static const char* value(const ::kinect::KinectCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2394b59af5274a4ULL;
  static const uint64_t static_value2 = 0x7f8538009ed2d9f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect::KinectCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect/KinectCommand";
  }

  static const char* value(const ::kinect::KinectCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect::KinectCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 start\n\
uint8 objNum\n\
";
  }

  static const char* value(const ::kinect::KinectCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect::KinectCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.objNum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct KinectCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect::KinectCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect::KinectCommand_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
    s << indent << "objNum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.objNum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_MESSAGE_KINECTCOMMAND_H
