// Generated by gencpp from file kinect/SensorCommand.msg
// DO NOT EDIT!


#ifndef KINECT_MESSAGE_SENSORCOMMAND_H
#define KINECT_MESSAGE_SENSORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinect
{
template <class ContainerAllocator>
struct SensorCommand_
{
  typedef SensorCommand_<ContainerAllocator> Type;

  SensorCommand_()
    : id(0)
    , begin(0)
    , finish(0)  {
    }
  SensorCommand_(const ContainerAllocator& _alloc)
    : id(0)
    , begin(0)
    , finish(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _begin_type;
  _begin_type begin;

   typedef uint8_t _finish_type;
  _finish_type finish;




  typedef boost::shared_ptr< ::kinect::SensorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect::SensorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SensorCommand_

typedef ::kinect::SensorCommand_<std::allocator<void> > SensorCommand;

typedef boost::shared_ptr< ::kinect::SensorCommand > SensorCommandPtr;
typedef boost::shared_ptr< ::kinect::SensorCommand const> SensorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect::SensorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect::SensorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kinect': ['/home/marouane/Documents/fp_workspace/rosCode/src/kinect/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect::SensorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect::SensorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect::SensorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect::SensorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect::SensorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect::SensorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect::SensorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25eb2b19b6f929cb1994bd90cac57780";
  }

  static const char* value(const ::kinect::SensorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25eb2b19b6f929cbULL;
  static const uint64_t static_value2 = 0x1994bd90cac57780ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect::SensorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect/SensorCommand";
  }

  static const char* value(const ::kinect::SensorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect::SensorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8 begin\n\
uint8 finish\n\
";
  }

  static const char* value(const ::kinect::SensorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect::SensorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.begin);
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SensorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect::SensorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect::SensorCommand_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "begin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.begin);
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_MESSAGE_SENSORCOMMAND_H
