// Generated by gencpp from file mitsubishi_melfa/PositionCommand.msg
// DO NOT EDIT!


#ifndef MITSUBISHI_MELFA_MESSAGE_POSITIONCOMMAND_H
#define MITSUBISHI_MELFA_MESSAGE_POSITIONCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mitsubishi_melfa
{
template <class ContainerAllocator>
struct PositionCommand_
{
  typedef PositionCommand_<ContainerAllocator> Type;

  PositionCommand_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , velocity_factor(0.0)  {
    }
  PositionCommand_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , velocity_factor(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _velocity_factor_type;
  _velocity_factor_type velocity_factor;




  typedef boost::shared_ptr< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PositionCommand_

typedef ::mitsubishi_melfa::PositionCommand_<std::allocator<void> > PositionCommand;

typedef boost::shared_ptr< ::mitsubishi_melfa::PositionCommand > PositionCommandPtr;
typedef boost::shared_ptr< ::mitsubishi_melfa::PositionCommand const> PositionCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mitsubishi_melfa

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mitsubishi_melfa': ['/home/marouane/Documents/fp_workspace/rosCode/src/mitsubishi_melfa/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63a595af437927f7d77813a9c7f45b16";
  }

  static const char* value(const ::mitsubishi_melfa::PositionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63a595af437927f7ULL;
  static const uint64_t static_value2 = 0xd77813a9c7f45b16ULL;
};

template<class ContainerAllocator>
struct DataType< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mitsubishi_melfa/PositionCommand";
  }

  static const char* value(const ::mitsubishi_melfa::PositionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z \n\
float32 velocity_factor\n\
";
  }

  static const char* value(const ::mitsubishi_melfa::PositionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.velocity_factor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PositionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mitsubishi_melfa::PositionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mitsubishi_melfa::PositionCommand_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "velocity_factor: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_factor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MITSUBISHI_MELFA_MESSAGE_POSITIONCOMMAND_H
