(cl:in-package mitsubishi_melfa-msg)
(cl:export '(ICONTROL_TYPE-VAL
          ICONTROL_TYPE
          TYPE_MONITOR1-VAL
          TYPE_MONITOR1
          TYPE_MONITOR2-VAL
          TYPE_MONITOR2
          TYPE_MONITOR3-VAL
          TYPE_MONITOR3
          TYPE_MONITOR4-VAL
          TYPE_MONITOR4
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROT_X-VAL
          ROT_X
          ROT_Y-VAL
          ROT_Y
          ROT_Z-VAL
          ROT_Z
          J1-VAL
          J1
          J2-VAL
          J2
          J3-VAL
          J3
          J4-VAL
          J4
          J5-VAL
          J5
          J6-VAL
          J6
))